[versions]
kotlinVer = "1.5.31"
# 7.1.0-beta04
agpVer = "7.0.4"
# 30.1.0-beta04
androidToolVer = "30.0.4"
polyfillVer = "0.4.1"
mockitoVer = "3.9.0"

[libraries]
android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "agpVer" }
android-tools-sdkcommon = { module = "com.android.tools:sdk-common", version.ref = "androidToolVer" }
android-tools-sdklib = { module = "com.android.tools:sdklib", version.ref = "androidToolVer" }
android-tools-bundletool = { module = "com.android.tools.build:bundletool", version = "1.6.0" }
kotlin-std = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlinVer" }
polyfill-main = { module = "me.2bab:polyfill", version.ref = "polyfillVer" }
junit = { module = "junit:junit", version = "4.12" }
mockito = { module = "org.mockito:mockito-core", version.ref = "mockitoVer" }
mockitoInline = { module = "org.mockito:mockito-inline", version.ref = "mockitoVer" }

[bundles]

[plugins]